global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'finance-api'
    static_configs:
      - targets: ['finance-api:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']