name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install ESLint globally
      run: npm install -g eslint
    
    - name: Run linting
      run: eslint .
    
    - name: Run tests
      run: npm test
    
    - name: Build Docker image
      run: docker build -t finance-tracker-api .